# All scheduled_time entries must be in UTC!
# http://rm.isr.ist.utl.pt/attachments/605/RockIn_2014_competition_schedule.pdf

- zone: Testing TestingTeam
  schedule:
    - { benchmark: HGTKMH, round: 1, run: 1, scheduled_time: 2015-12-31 00:00:00, team: TestingTeam }
    - { benchmark: HWV,    round: 1, run: 1, scheduled_time: 2015-12-31 00:01:00, team: TestingTeam }
    - { benchmark: HCFGAC, round: 1, run: 1, scheduled_time: 2015-12-31 00:02:00, team: TestingTeam }
    - { benchmark: HOPF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:03:00, team: TestingTeam }
    - { benchmark: HNF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:04:00, team: TestingTeam }
    - { benchmark: HSUF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:05:00, team: ALL }

- zone: Testing b-it-bots
  schedule:
    - { benchmark: HGTKMH, round: 1, run: 1, scheduled_time: 2015-12-31 00:00:00, team: b-it-bots }
    - { benchmark: HWV,    round: 1, run: 1, scheduled_time: 2015-12-31 00:01:00, team: b-it-bots }
    - { benchmark: HCFGAC, round: 1, run: 1, scheduled_time: 2015-12-31 00:02:00, team: b-it-bots }
    - { benchmark: HOPF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:03:00, team: b-it-bots }
    - { benchmark: HNF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:04:00, team: b-it-bots }
    - { benchmark: HSUF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:05:00, team: ALL }

- zone: Testing BARC
  schedule:
    - { benchmark: HGTKMH, round: 1, run: 1, scheduled_time: 2015-12-31 00:00:00, team: BARC }
    - { benchmark: HWV,    round: 1, run: 1, scheduled_time: 2015-12-31 00:01:00, team: BARC }
    - { benchmark: HCFGAC, round: 1, run: 1, scheduled_time: 2015-12-31 00:02:00, team: BARC }
    - { benchmark: HOPF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:03:00, team: BARC }
    - { benchmark: HNF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:04:00, team: BARC }
    - { benchmark: HSUF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:05:00, team: ALL }

- zone: Testing Donaxi
  schedule:
    - { benchmark: HGTKMH, round: 1, run: 1, scheduled_time: 2015-12-31 00:00:00, team: Donaxi }
    - { benchmark: HWV,    round: 1, run: 1, scheduled_time: 2015-12-31 00:01:00, team: Donaxi }
    - { benchmark: HCFGAC, round: 1, run: 1, scheduled_time: 2015-12-31 00:02:00, team: Donaxi }
    - { benchmark: HOPF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:03:00, team: Donaxi }
    - { benchmark: HNF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:04:00, team: Donaxi }
    - { benchmark: HSUF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:05:00, team: ALL }

- zone: Testing homer
  schedule:
    - { benchmark: HGTKMH, round: 1, run: 1, scheduled_time: 2015-12-31 00:00:00, team: homer }
    - { benchmark: HWV,    round: 1, run: 1, scheduled_time: 2015-12-31 00:01:00, team: homer }
    - { benchmark: HCFGAC, round: 1, run: 1, scheduled_time: 2015-12-31 00:02:00, team: homer }
    - { benchmark: HOPF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:03:00, team: homer }
    - { benchmark: HNF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:04:00, team: homer }
    - { benchmark: HSUF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:05:00, team: ALL }

- zone: Testing Pumas
  schedule:
    - { benchmark: HGTKMH, round: 1, run: 1, scheduled_time: 2015-12-31 00:00:00, team: Pumas }
    - { benchmark: HWV,    round: 1, run: 1, scheduled_time: 2015-12-31 00:01:00, team: Pumas }
    - { benchmark: HCFGAC, round: 1, run: 1, scheduled_time: 2015-12-31 00:02:00, team: Pumas }
    - { benchmark: HOPF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:03:00, team: Pumas }
    - { benchmark: HNF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:04:00, team: Pumas }
    - { benchmark: HSUF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:05:00, team: ALL }

- zone: Testing SocRob
  schedule:
    - { benchmark: HGTKMH, round: 1, run: 1, scheduled_time: 2015-12-31 00:00:00, team: SocRob }
    - { benchmark: HWV,    round: 1, run: 1, scheduled_time: 2015-12-31 00:01:00, team: SocRob }
    - { benchmark: HCFGAC, round: 1, run: 1, scheduled_time: 2015-12-31 00:02:00, team: SocRob }
    - { benchmark: HOPF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:03:00, team: SocRob }
    - { benchmark: HNF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:04:00, team: SocRob }
    - { benchmark: HSUF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:05:00, team: ALL }

- zone: Testing Ursus
  schedule:
    - { benchmark: HGTKMH, round: 1, run: 1, scheduled_time: 2015-12-31 00:00:00, team: Ursus }
    - { benchmark: HWV,    round: 1, run: 1, scheduled_time: 2015-12-31 00:01:00, team: Ursus }
    - { benchmark: HCFGAC, round: 1, run: 1, scheduled_time: 2015-12-31 00:02:00, team: Ursus }
    - { benchmark: HOPF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:03:00, team: Ursus }
    - { benchmark: HNF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:04:00, team: Ursus }
    - { benchmark: HSUF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:05:00, team: ALL }

- zone: Testing Watermelon
  schedule:
    - { benchmark: HGTKMH, round: 1, run: 1, scheduled_time: 2015-12-31 00:00:00, team: Watermelon }
    - { benchmark: HWV,    round: 1, run: 1, scheduled_time: 2015-12-31 00:01:00, team: Watermelon }
    - { benchmark: HCFGAC, round: 1, run: 1, scheduled_time: 2015-12-31 00:02:00, team: Watermelon }
    - { benchmark: HOPF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:03:00, team: Watermelon }
    - { benchmark: HNF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:04:00, team: Watermelon }
    - { benchmark: HSUF,   round: 1, run: 1, scheduled_time: 2015-12-31 00:05:00, team: ALL }
